apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaml-prompt-mcp
spec:
  template:
    spec:
      containers:
      - name: yaml-prompt-mcp
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
